// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NerdSupport.Specs.Done
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PrioriteringAvFragorFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PrioriteringAvArende.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("sv-SE"), "Prioritering av frågor", "\r\nFör nörden ska vara på rätt fråga\r\nSom system\r\nSka jag räkna ut prioriteringen " +
                    "på frågorna enligt ett regelsystem", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Prioritering av frågor")))
            {
                NerdSupport.Specs.Done.PrioriteringAvFragorFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 9
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Namn",
                        "Prioritet"});
            table1.AddRow(new string[] {
                        "8 timmars regeln",
                        "1"});
            table1.AddRow(new string[] {
                        "Dygnsregeln",
                        "5"});
            table1.AddRow(new string[] {
                        "VIP avsändar regeln",
                        "78"});
#line 10
testRunner.Given("att ett serviceavtal har följande SLA regler", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Beräkna prioritet när en av SLA reglerna bryts")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Prioritering av frågor")]
        public virtual void BeraknaPrioritetNarEnAvSLAReglernaBryts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Beräkna prioritet när en av SLA reglerna bryts", new string[] {
                        "prioritering",
                        "currentiteration"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 18
 testRunner.Given("att \"8 timmars regeln\" inte uppfylls");
#line 19
 testRunner.When("Systemet beräknar frågans prioritet");
#line 20
 testRunner.Then("är frågans prioritet 1");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Beräkna prioritet när flera SLA regler inte uppfylls")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Prioritering av frågor")]
        public virtual void BeraknaPrioritetNarFleraSLAReglerInteUppfylls()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Beräkna prioritet när flera SLA regler inte uppfylls", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 23
 testRunner.Given("att \"8 timmars regeln\" inte uppfylls");
#line 24
 testRunner.And("att \"Dygnsregeln\" inte uppfylls");
#line 25
 testRunner.When("Systemet beräknar frågans prioritet");
#line 26
 testRunner.Then("är frågans prioritet 6");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Inga regler brutna")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Prioritering av frågor")]
        public virtual void IngaReglerBrutna()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inga regler brutna", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 9
this.FeatureBackground();
#line 29
 testRunner.Given("att inga regler är brutna");
#line 30
 testRunner.When("Systemet beräknar frågans prioritet");
#line 31
 testRunner.Then("är frågans prioritet 0");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
